# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '27th_iOS_seminar_week04' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 27th_iOS_seminar_week04
pod 'FSCalendar'

end
